#!/bin/sh

trap "echo '\n[경고]\n인터럽트를 발생시키지 마세요.\n'" INT TSTP TERM

fbterm
name=$(whoami)
sudo sed -i '/init_account2/d' /etc/bash.bashrc
sudo sed -i "/font-size/ c\font-size=20" ~/.fbtermrc
sudo sed -i '/rookie/d' /etc/sudoers
rm -f ./init_account2

sudo sed -i'' -r -e "/fbterm/i\/home/${name}/init_account3" /etc/bash.bashrc
printf "설정을 마치기 위해 재부팅을 실행합니다.\n\n"
printf "다시 재부팅이 완료되면 방금 생성한 아이디로 로그인 해주세요.\n\n"
printf "재부팅 이후 모든 설정이 완료된 후에는 영어로 결과 메시지가 출력됩니다.\n"
printf "원활한 사용을 위해 그 후에 한번 더 재부팅하는 것을 권장드립니다.\n"
printf "(재부팅하지 않으면 exit 입력 시 Trainer가 한번 더 실행됨)\n\n"
printf "Enter를 입력하면 재부팅이 시작됩니다.\n"
read trash
printf "3 초후에 종료됩니다.\n\n"
sleep 1
printf "2 초후에 종료됩니다.\n\n"
sleep 1
printf "1 초후에 종료됩니다.\n\n"
sleep 1

sudo init 6
