#!/bin/sh
trap "echo '\n[경고]\n인터럽트를 발생시키지 마세요.\n'" INT TSTP TERM

# 계정 이름을 저장
name=$(whoami)

# 'rookie' 계정 삭제
# init_account 관련 내용 bash.bashrc에서 모두 삭제
# 설치를 진행하기 위해 NOPASSWD로 sudoers에 등록된 내용 모두 삭제
# 쉘 스크립트 파일 삭제
sudo userdel -r rookie > /dev/null 2>&1
sudo sed -i '/init_account/d' /etc/bash.bashrc
sudo sed -i '/NOPASSWD/d' /etc/sudoers
rm -f ./init_account3

clear

# 새로운 계정 생성 완료 후 메시지 출력
# 이 때는 fbterm이 실행된 상태가 아니기 때문에 문장은 영어로 출력해야함
printf "********************************************************************\n"
printf "Success all init settings\n"
printf "If you typing 'trainer' on console, run BoB Linux Trainer\n"
printf "There are more details in '/home/${name}/README'\n" 
printf "Press Enter to start\n"
printf "********************************************************************\n"

# Enter를 입력받기 위한 구문
read input

exit
