#!/bin/sh
trap "echo '\n[경고]\n인터럽트를 발생시키지 마세요.\n'" INT TSTP TERM

name=$(whoami)
sudo userdel -r rookie > /dev/null 2>&1
sudo sed -i '/init_account/d' /etc/bash.bashrc
sudo sed -i '/NOPASSWD/d' /etc/sudoers
rm -f ./init_account3
clear
printf "********************************************************************\n"
printf "Success all init settings\n"
printf "If you typing 'trainer' on console, run BoB Linux Trainer\n"
printf "There are more details in '/home/${name}/README'\n" 
printf "Press Enter to start\n"
printf "********************************************************************\n"
read input
fbterm
exit
