sudo apt install apt-utils -y
sudo apt install gdb -y
sudo apt install at -y
sudo apt install apache -y
sudo apt install ftp -y
sudo apt install nginx -y
sudo apt install mysql-server -y
sudo apt install wget -y
sudo apt install curl -y
sudo apt install ufw -y
sudo apt install ace -y
sudo apt install arp-scan -y
sudo apt install braa -y
sudo apt install dmitry -y
sudo apt install dnsenum -y
sudo apt install dnsmap -y
sudo apt install dnsrecon -y
sudo apt install dnstracer -y
sudo apt install dnswalk -y
sudo apt install hping3 -y
sudo apt install masscan -y
sudo apt install nbtscan -y
sudo apt install nikto -y
sudo apt install nmap -y
sudo apt install p0f -y
sudo apt install parsero -y
sudo apt install recon-ng -y
sudo apt install smbmap -y
sudo apt install sslsplit -y
sudo apt install thc-ipv6 -y
sudo apt install tshark -y
sudo apt install lynis -y
sudo apt install sqlmap -y
sudo apt install backdoor-factory -y
sudo apt install aircrack-ng -y
sudo apt install airgraph-ng -y
sudo apt install cowpatty -y
sudo apt install freeradius -y
sudo apt install gqrx-sdr -y
sudo apt install hostapd -y
sudo apt install kismet -y
sudo apt install mdk3 -y
sudo apt install mfcuk -y
sudo apt install mfoc -y
sudo apt install multimon-ng -y
sudo apt install pixiewps -y
sudo apt install reaver -y
sudo apt install chntpw -y
sudo apt install dc3dd -y
sudo apt install extundelete -y
sudo apt install foremost -y
sudo apt install galleta -y
sudo apt install cutycapt -y
sudo apt install dirb -y
sudo apt install gobuster -y
sudo apt install websploit -y
sudo apt install wfuzz -y
sudo apt install whatweb -y
sudo apt install dhcpig -y
sudo apt install slowhttptest -y
sudo apt install t50 -y
sudo apt install termineter -y
sudo apt install ettercap-text-only -y
sudo apt install mitmproxy -y
sudo apt install brutespray -y
sudo apt install cewl -y
sudo apt install cmospwd -y
sudo apt install crunch -y
sudo apt install hashcat -y
sudo apt install maskprocessor -y
sudo apt install ncrack -y
sudo apt install ophcrack -y
sudo apt install patator -y
sudo apt install polenum -y
sudo apt install statsprocessor -y
sudo apt install cryptcat -y
sudo apt install dns2tcp -y
sudo apt install httptunnel -y
sudo apt install rbd -y
sudo apt install weevely -y
sudo apt install apktool -y
sudo apt install valgrind -y
sudo apt install yara -y
sudo apt install dos2unix -y
